language: python
python:
  - 2.7
  - 3.2
  - 3.5
install:
  - pip install psutil six
  - python setup.py develop
script: python setup.py test
notifications:
  slack:
    secure: A6A3o/F3VyRnmhL2/9QXkXTi70ZwJIUQGts9BWPfgkiBBDATKe7OijZms+b0xFUrJ2DKHyHocLBf4IVnoFihwyQy05vv3fOjpJlBtRaRifsgFh8gQw1hQ+1LENJQj0QUk+kEJLAtZ3PY/KyTBZUeSo/ZruMmTQAWmpUAKypIzkUTjjdE+Kh0w9VYaUfOgd2fmSXetCda/FvKEob1eAhjYTvAgfp8U4yS+SrHwvDnxLNwStZdfIKssuES8CiA/u7gzNdZphQS8A5XC+FWfz3sXSCcqG6Cp62NPhorEYXpUalzZ40pgTI6aDkcvmuT+ke+B5RGDpVYgx2mBlqPzgynosd20DlRgrN4rUE6vn8YSi6Lny1TmZURGFgckioBU5C/JCEbgKIADSQ+ZZ2YdDQ0SSduDqBi4wdxapDMCAyLAVyZga5Uxjxuc4gy1UHfGhpbXYrg0WYkmqkp6Z5ocz77LCD4fBIox27ng1e3ZeV+m6W7Z2HffvRlwndaXnkvfcSQF+6zjnhNnbrImUvshbDGSCM4jGMlQReajs5yL+qws5ePnGa2h/2Fq/FfpiqS1wCK3sEcRdk9FjMstC8REpThuFiK8z/FRTtdhHx4tiQW3MVCQayhN/yIxTKxYPh8Md7yg0N/Qahtifb4mvl+cvHfM1G9Ksnx4X1SlE19JS9tTmU=
